Romain-Ber/GameRental

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/pages/home.html.erb
- config/initializers/devise.rb
- db/migrate/20240226152927_add_username_to_users.rb
- db/schema.rb
add column username to users
log in - log out - sign up - forgot your password
> add column username to users - login

- app/models/review.rb
- db/migrate/20240227103654_create_reviews.rb
- db/migrate/20240227104058_add_rating_to_review.rb
- db/schema.rb
- test/models/review_test.rb
J'ai créé le model de review avec sa validation + ajouté rating !
> model review created

- app/models/user.rb
- app/views/devise/registrations/new.html.erb
validates :username, presence: true
validates :email, presence: true
validates :encrypted_password, presence: true
> add validates to users

- app/models/wishlist.rb
- db/migrate/20240227112545_create_wishlists.rb
- db/schema.rb
- test/models/wishlist_test.rb
belongs_to :users
has_many :games
> add wishlist model

- app/models/booking.rb
- db/migrate/20240227112012_create_bookings.rb
- test/models/booking_test.rb
> Game Model

- app/models/booking.rb
- app/models/game.rb
- app/models/review.rb
- app/models/user.rb
- app/models/wishlist.rb
- db/migrate/20240227132737_change_foreign_key_to_games.rb
- db/migrate/20240227134713_drop_reviews_table.rb
- db/schema.rb
> drop review table and add models associations

- db/migrate/20240227151315_remove_review_id_from_bookings.rb
- db/schema.rb
- db/seeds.rb
> game seeding and remove review id from bookings

- app/models/game.rb
- db/migrate/20240227153737_add_references_to_wishlists.rb
- db/migrate/20240227155003_rename_type_column_in_games.rb
- db/schema.rb
- db/seeds.rb
> change to column type in games, add wishlist associations + seed rework

- app/assets/stylesheets/components/_game_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/games/index.html.erb
> added game cards

- app/models/user.rb
- db/migrate/20240228100753_add_address_to_users.rb
- db/migrate/20240228101250_add_lat_long_to_users.rb
- db/schema.rb
- db/seeds.rb
add address, lat, long to users
> add address, lat, long to users

- app/controllers/bookings_controller.rb
- app/models/game.rb
- app/models/user.rb
- app/models/wishlist.rb
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- config/routes.rb
- db/migrate/20240228105535_add_message_to_booking.rb
- db/schema.rb
- db/seeds.rb
add make a booking feature
db change to user
seed user
associations
> I can make a booking

- app/controllers/bookings_controller.rb
- app/views/games/show.html.erb
> show retouch

- app/controllers/users_controller.rb
- db/seeds.rb
debugged seed + remove user controller
> debugged seed + remove user controller

- app/controllers/bookings_controller.rb
- app/views/bookings/pending_booking.html.erb
- app/views/bookings/pending_client.html.erb
- app/views/games/index.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- db/migrate/20240228155021_add_status_to_booking.rb
- db/schema.rb
> split bookings user/client

- app/views/bookings/pending_booking.html.erb
- app/views/bookings/pending_client.html.erb
- app/views/games/index.html.erb
- app/views/games/show.html.erb
> implement some link_to

- app/controllers/games_controller.rb
- app/views/games/edit.html.erb
- app/views/games/show.html.erb
> edit & update game

- app/assets/stylesheets/components/_booking_card.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/pending_booking.html.erb
- config/routes.rb
- db/migrate/20240228194630_change_booked_to_status_in_bookings.rb
- db/schema.rb
added view to pending bookings
> added view to pending bookings

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/bookings/show.html.erb
- db/seeds.rb
bookings seed, booking model change, show rework and maps into show
> bookings seed, booking model change, show rework and maps into show

- app/views/games/index.html.erb
- db/seeds.rb
added user-owner exclusions (cannot see/rent own games)
> added exclusions

- app/views/bookings/pending_client.html.erb
> client list

- app/controllers/bookings_controller.rb
- app/views/bookings/pending_booking.html.erb
- app/views/bookings/pending_client.html.erb
- app/views/bookings/show.html.erb
added client view by splitting show through controller parameter
> added client view by splitting show through controller parameter

- app/controllers/bookings_controller.rb
- app/controllers/games_controller.rb
- app/views/games/my_offers.html.erb
- app/views/games/show.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- db/seeds.rb
added owner list, path, view rework, more game seeds
> added owner list, path, view rework, more game seeds

- app/controllers/bookings_controller.rb
- app/controllers/games_controller.rb
- app/views/bookings/pending_booking.html.erb
- app/views/bookings/pending_client.html.erb
- app/views/bookings/show.html.erb
- app/views/games/index.html.erb
- app/views/games/my_offers.html.erb
- app/views/games/show.html.erb
- config/routes.rb
split games show for user/owner, added routes
> split games show for user/owner, added routes

- app/controllers/bookings_controller.rb
- app/controllers/games_controller.rb
- app/views/pages/home.html.erb
removed useless variables from controllers
> removed useless variables from controllers

- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
- config/routes.rb
> bookings can be canceled

- app/views/games/edit.html.erb
- app/views/games/show.html.erb
> moved a button

- app/controllers/wishlists_controller.rb
- app/views/pages/home.html.erb
- app/views/wishlists/index.html.erb
- config/routes.rb
- test/controllers/wishlists_controller_test.rb
wishlist controller, route, view
> wishlist controller, route, view

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_new_game.scss
- app/views/games/new.html.erb
mise en page du form de new game
> new game form
